/**
 * PosesTab — the pose presets: this codebase's activity library.
 *
 * A preset maps free-text activity ("leaning against the coffee machine") onto
 * a canonical key, a body-pose prompt (for image generation) and an ANIMATION
 * kind that a 3D client turns into a clip. Synonyms make the free text land on
 * the right key; unknown activities are auto-generated by the LLM (those show
 * up here as "generated" and can be corrected).
 *
 * The animation vocabulary is NOT hardcoded: the dropdown is filled from the
 * clips that actually exist (/assets/animation-clips). Empty is valid and
 * means "the client guesses from the text" — the old fallback.
 */
import { useCallback, useEffect, useMemo, useState } from 'react'
import { useI18n } from '../../i18n/I18nProvider'
import { apiDelete, apiGet, apiPost, apiPut } from '../../lib/api'
import { useToast } from '../../lib/Toast'
import { Field } from '../../components/Field'
import { DetailToolbar } from '../../components/DetailToolbar'
import { ListHeader } from '../../components/ListHeader'

interface Pose {
  key: string
  prompt: string
  synonyms: string[]
  animation: string
  solo?: boolean
  is_default?: boolean
  source: 'curated' | 'generated'
}

interface PosesData {
  presets: Pose[]
  kinds: string[]
}

const EMPTY: Pose = { key: '', prompt: '', synonyms: [], animation: '', source: 'curated' }

export function PosesTab() {
  const { t } = useI18n()
  const { toast } = useToast()
  const [data, setData] = useState<PosesData>({ presets: [], kinds: [] })
  const [selected, setSelected] = useState<string>('')
  const [draft, setDraft] = useState<Pose | null>(null)
  const [isNew, setIsNew] = useState(false)
  const [search, setSearch] = useState('')
  const [onlyMissing, setOnlyMissing] = useState(false)

  const load = useCallback(async () => {
    try {
      setData(await apiGet<PosesData>('/poses'))
    } catch (e) {
      toast(t('Error') + ': ' + (e as Error).message, 'error')
    }
  }, [t, toast])

  useEffect(() => {
    load()
  }, [load])

  const list = useMemo(() => {
    const q = search.trim().toLowerCase()
    return data.presets.filter((p) => {
      if (onlyMissing && p.animation) return false
      if (!q) return true
      return (
        p.key.includes(q) ||
        p.prompt.toLowerCase().includes(q) ||
        p.synonyms.some((s) => s.includes(q))
      )
    })
  }, [data.presets, search, onlyMissing])

  const missingCount = useMemo(
    () => data.presets.filter((p) => !p.animation).length,
    [data.presets],
  )

  const select = useCallback(
    (key: string) => {
      const p = data.presets.find((x) => x.key === key)
      if (!p) return
      setSelected(key)
      setIsNew(false)
      setDraft({ ...p, synonyms: [...p.synonyms] })
    },
    [data.presets],
  )

  const addNew = useCallback(() => {
    setSelected('')
    setIsNew(true)
    setDraft({ ...EMPTY })
  }, [])

  const save = useCallback(async () => {
    if (!draft) return
    const key = draft.key.trim().toLowerCase()
    if (!key || !draft.prompt.trim()) {
      toast(t('Key and pose text are required'), 'error')
      return
    }
    try {
      const body = {
        key,
        prompt: draft.prompt,
        synonyms: draft.synonyms,
        animation: draft.animation,
      }
      if (isNew) await apiPost('/poses', body)
      else await apiPut(`/poses/${encodeURIComponent(key)}`, body)
      toast(t('Saved'))
      setIsNew(false)
      setSelected(key)
      await load()
    } catch (e) {
      toast(t('Error') + ': ' + (e as Error).message, 'error')
    }
  }, [draft, isNew, load, t, toast])

  const remove = useCallback(async () => {
    if (!draft || isNew) return
    try {
      await apiDelete(`/poses/${encodeURIComponent(draft.key)}`)
      toast(t('Deleted'))
      setDraft(null)
      setSelected('')
      await load()
    } catch (e) {
      toast(t('Error') + ': ' + (e as Error).message, 'error')
    }
  }, [draft, isNew, load, t, toast])

  const upd = useCallback(<K extends keyof Pose>(k: K, v: Pose[K]) => {
    setDraft((prev) => (prev ? { ...prev, [k]: v } : prev))
  }, [])

  return (
    <div className="ga-twocol">
      <aside className="ga-twocol-left">
        <ListHeader title={t('Poses')} onNew={addNew} />
        <p className="ga-sched-muted">
          {t('A pose maps free-text activities onto a body posture (for image generation) and an animation kind (for 3D clients). Unknown activities are added by the LLM automatically.')}
        </p>
        <div style={{ display: 'flex', flexDirection: 'column', gap: 6, marginBottom: 8 }}>
          <input
            className="ga-input"
            placeholder={t('Search…')}
            value={search}
            onChange={(e) => setSearch(e.target.value)}
          />
          <label style={{ display: 'flex', gap: 6, alignItems: 'center', fontSize: '0.8em' }}>
            <input
              type="checkbox"
              checked={onlyMissing}
              onChange={(e) => setOnlyMissing(e.target.checked)}
            />
            <span>
              {t('Without animation')} ({missingCount})
            </span>
          </label>
        </div>
        <ul className="ga-list">
          {!list.length ? <li className="ga-list-empty">{t('No entries')}</li> : null}
          {list.map((p) => (
            <li key={p.key}>
              <button
                type="button"
                className={`ga-list-row${selected === p.key ? ' is-active' : ''}`}
                onClick={() => select(p.key)}
              >
                <span className="ga-list-row-main">
                  <code>{p.key}</code>
                  <span className="ga-list-row-sub" style={{ opacity: p.animation ? 1 : 0.4 }}>
                    — {p.animation || t('no animation')}
                  </span>
                </span>
                <span className={`ga-source ga-source-${p.source}`}>{p.source}</span>
              </button>
            </li>
          ))}
        </ul>
      </aside>

      <section className="ga-twocol-right">
        {!draft ? (
          <div className="ga-placeholder">
            {t('Pick a pose or create a new one.')}
          </div>
        ) : (
          <>
            <DetailToolbar
              title={isNew ? t('New pose') : draft.key}
              onSave={save}
              onDelete={isNew ? undefined : remove}
            />
            <div className="ga-form">
              <div className="ga-form-row">
                <Field label={t('Key')} hint={t('Canonical activity name, lowercase (e.g. sitting).')}>
                  <input
                    className="ga-input"
                    value={draft.key}
                    disabled={!isNew}
                    onChange={(e) => upd('key', e.target.value)}
                  />
                </Field>
                <Field
                  label={t('Animation')}
                  hint={t('Clip kind a 3D figure plays. Options come from the clips present in shared/models/clips. Empty = the client guesses from the text.')}
                >
                  <select
                    className="ga-input"
                    value={draft.animation}
                    onChange={(e) => upd('animation', e.target.value)}
                  >
                    <option value="">{t('— none (client guesses) —')}</option>
                    {data.kinds.map((k) => (
                      <option key={k} value={k}>
                        {k}
                      </option>
                    ))}
                    {/* keep an animation whose clip has since been removed */}
                    {draft.animation && !data.kinds.includes(draft.animation) ? (
                      <option value={draft.animation}>{draft.animation} ({t('no clip')})</option>
                    ) : null}
                  </select>
                </Field>
              </div>

              <Field
                label={t('Pose text')}
                hint={t('Body posture for the image generation — arms, legs, posture. Third person, no names.')}
              >
                <textarea
                  className="ga-textarea"
                  rows={3}
                  value={draft.prompt}
                  onChange={(e) => upd('prompt', e.target.value)}
                />
              </Field>

              <Field
                label={t('Synonyms')}
                hint={t('Comma-separated. Free-text activities matching one of these land on this pose.')}
              >
                <input
                  className="ga-input"
                  value={draft.synonyms.join(', ')}
                  onChange={(e) =>
                    upd(
                      'synonyms',
                      e.target.value.split(',').map((s) => s.trim()).filter(Boolean),
                    )
                  }
                />
              </Field>

              <div className="ga-form-hint">
                {draft.source === 'generated'
                  ? t('LLM-generated entry. It was created when this activity first showed up.')
                  : t('Curated entry (in git).')}
              </div>
            </div>
          </>
        )}
      </section>
    </div>
  )
}
